### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/gulp-task-runner#1]
![screenshot from 2016-09-22 17-50-04](https://cloud.githubusercontent.com/assets/217543/18755572/0f71e7a0-80ed-11e6-9a57-500519112bcc.png)

**Comment by NicolasPetton** [comment]
do you get the same escape characters with `M-x compile RET gulp`?

**Comment by NicolasPetton** [comment]
Also, what version of Emacs are you using?

**Comment by DamienCassou** [comment]
Indeed, `M-x compile RET gulp` has the same problem:

![screenshot from 2016-09-23 12-12-06](https://cloud.githubusercontent.com/assets/217543/18782478/fe7add36-8186-11e6-9a1f-256ac4e43603.png)

I'm on `GNU Emacs 25.1.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-09-20`.

**Comment by NicolasPetton** [comment]
I do not know why, and I don't have this issue on Emacs 25.1.

**Comment by vitaminless** [comment]
Same issue here with Emacs 25.1.1 and found a solution http://stackoverflow.com/questions/13397737/ansi-coloring-in-compilation-mode#13408008.

``` elisp
(defun my-compilation-filter-hook ()
  "Compilation filter hook."
  (read-only-mode -1)
  (ansi-color-apply-on-region compilation-filter-start (point))
  (read-only-mode 1))
(add-hook 'compilation-filter-hook 'my-compilation-filter-hook)
```

**Comment by DamienCassou** [comment]
Thanks for the workaround. It works for me.

**Comment by NicolasPetton** [comment]
Damien Cassou notifications@github.com writes:

> Thanks for the workaround. It works for me.

Should we close the issue? (I still don't have that problem on Emacs
25.1, BTW).

Cheers,
Nico

**Comment by vitaminless** [comment]
@NicolasPetton 

> Should we close the issue? (I still don't have that problem on Emacs 25.1, BTW).

I would suggest the workaround in the Readme, anyway I would close the issue.

**Comment by NicolasPetton** [comment]
Yes, closing.
